### ISSUE TITLE
[Onion Messenger 구현] 본격적 코드 작성 및 잘못된 프레임 수정

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018s-onion-team2#13]
프레임 부분이 거의 작성되어 이슈를 남깁니다.

저는 대략적으로 다음 역할군을 가지고 역할을 부여할 생각입니다. 
(뒤에 괄호는 제가 생각한 적임자 입니다.)

Communication : 각종 프로토콜을 이용하여 데이터를 주고 받는 부분 (@elmisty, @hexife - client/server 구분 무)
Parser : 들어온 데이터를 Flag를 이용해 파싱 및 자료구조에 저장(@hongsh93 )
통신부 등 thread 관리 : 각 파츠(수신단, 송신단, heartbeat)가 각 thread 또는 process로 daemonize 되어 돌아갈 수 있도록 하는 부분 (@leeswimming)

미할당 (빠르게 끝난 사람이 붙을 예정)
gpg 연동
Storage
ui

부디 각자 "이것만 하면 됨" 이라는 생각보다, 이 프로젝트 전체를 보시고 코딩에 임해주셨으면 합니다.. 
열심히 해서 월요일 까지는 전송 테스트 등을 할 수 있도록 합시다.

그리고 프레임 코드 중에 잘못된 부분이 있을 수 있습니다.( 변수 이름이 헤더와 코드가 다름 등)
그 부분은 수정해서 풀리퀘 날려주시면 감사 드리겠습니다. (한번 쭉 보고 수정 다 하신 후에 보내주세요)

**Comment by Hexife** [comment]
의견 주시면 의논하는데 반영하겠습니다

**Comment by Hexife** [comment]
### Client
- [ ] client/config
- [ ] client/gpg.cc
- [ ] client/gpg.hh
- [ ] client/heartbeat.cc
- [ ] client/heartbeat.hh
- [ ] client/main.cc
- [ ] client/message.cc
- [ ] client/message.hh
- [ ] client/nodelist.cc
- [ ] client/nodelist.hh
- [ ] client/parser.cc
- [ ] client/parser.hh
- [ ] client/storage.cc
- [ ] client/storage.hh
- [ ] client/transmission.cc
- [ ] client/transmission.hh
- [ ] client/ui.cc
- [ ] client/ui.hh

### Server
- [ ] server/hbchecker.cc
- [ ] server/hbchecker.hh
- [ ] server/main.cc
- [ ] server/nodelist.cc
- [ ] server/nodelist.hh

**Comment by leeswimming** [comment]
오늘 미팅에서 이야기된 대로 내일까지 저는 client side 부분을 모두 구현해두도록 하겠습니다.

**Comment by leeswimming** [comment]
#14 와 같은 이유로 이슈를 종료하도록 하겠습니다.
