### ISSUE TITLE
Checkpoint comment

### ISSUE THREAD

**Issue by sangkilc** [KAIST-IS521/2018s-onion-team2#21]
1. 컴파일 조차 안되는 상황. 간단한 프로토타입을 만들고 기능을 더하는 식으로 발전시키는 것이 좋습니다.

2. 진도가 너무 느려보입니다.

3. 몇몇 학생은 contribution이 너무 부족합니다.

4. 어제 남긴 코멘트에 대답조차 하지 않는 상황?

**Comment by leeswimming** [comment]
네 커멘트 참고해서 좀 더 좋은 방향으로 진행할 수 있도록 하겠습니다.
감사합니다.

**Comment by sangkilc** [comment]
아까 코멘트에 추가해서, 좀 더 구체적으로 말씀드리면 issue가 너무 단조롭고 진행상황을 알기 어려운 것 같습니다.

최종 발표에서 보고 싶은 것들 입니다:
- 제품 이름?
- 제품에 대한 기술적 특장점?
- 제품에 대한 멤버들의 열정

**Comment by leeswimming** [comment]
넵 조교님께서도 어제 그렇게 말씀해주셔서 내일 중으로 반영할 예정이었습니다.
감사합니다.

**Comment by soomin-kim** [comment]
이것도 닫겠습니다.
