### ISSUE TITLE
[Onion Messenger 구현] Client UI 및 Prototype

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-onion-team2#22]
해당 부분은 prototype 브랜치에서 개발될 예정입니다.

**Comment by leeswimming** [comment]
프로토타입 완성 중 ... gpg encryption 문제로 난항을 겪고 있음

**Comment by leeswimming** [comment]
We have solved a null character handling problem. We are keep working on the integration and the bug fix.

**Comment by soomin-kim** [comment]
얘는 닫습니다
