### ISSUE TITLE
[Onion Messenger 구현] Client Heartbeat

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-onion-team2#26]
Client Side의 heartbeat receiving & sending part는 client_heartbeat 브랜치에서 구현할 예정입니다.

**Comment by Hexife** [comment]
현재 기초적인 구현은 완료 되었으며, non-ascii 처리에 대한 버그 처리 진행 중입니다.

**Comment by Hexife** [comment]
송수신 테스트 완료했습니다. 버그는 테스트 코드가 잘못 짜여져서 오인한 것으로 보이며, Parser 가 완성 되면 처리하는 로직을 구현하겠습니다. 이부분이 완성되면 heartbeat 파트는 끝납니다.

**Comment by leeswimming** [comment]
Please make a PR for the updated code. I cannot compile due to syntax errors in heartbeat.hh

**Comment by Hexife** [comment]
#40 PR 완료 및 추가 오타가 발견되어 수정하였습니다. 수정된 부분은 추후에 PR로 올리겠습니다.

**Comment by Hexife** [comment]
Client Heartbeat의 구현이 끝났습니다. #45
