### ISSUE TITLE
[Onion Messenger 구현] Transmssion Performance

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-onion-team2#27]
Transmission 과정에서 pthread가 사용되는 방법을 조금 바꿀 필요가 있어보입니다.  transmission 브랜치에서 진행하도록 하겠습니다.

**Comment by Hexife** [comment]
자세한 조언을 해주시면 반영하겠습니다.

**Comment by leeswimming** [comment]
socket programming을 위한 모든 코드가 수정되었으므로 해당 이슈를 종료합니다.
