### ISSUE TITLE
[Onion Messenger 구현] Server Heartbeat

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-onion-team2#28]
Server Side의 heartbeat listening과 sending 하는 부분은 server_heartbeat에서 진행하겠습니다.

**Comment by sangkilc** [comment]
I expect to see at least some short response from the assignee, if the issue is assigned 11 hours ago at the moment of writing. Be active and show your endeavor.

**Comment by elmisty** [comment]
확인했습니다.  Sever Sending에 대한 테스팅은 Node List에 대한 코드 테스팅 후 진행하도록 하겠습니다. 이후 추가 진행상황 코맨트를 통해 지속적으로 업로드 하겠습니다.

**Comment by leeswimming** [comment]
Since this issue is out of date, I close this issue.
