### ISSUE TITLE
[Onion Messenger 구현] Server Nodelist

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-onion-team2#29]
ServerSide에서 Nodelist를 유지하고 업데이트하는 부분은 server_nodelist 브랜치에서 진행하겠습니다.

**Comment by elmisty** [comment]
네 알겠습니다 노드는 해당 브랜치를 이용해 작성토록 하겠습니다. 현재 노드 테스트 중에 있으며, 코드가 제대로 동작이 되는지 확인 후 결과 말씀드리겠습니다.

**Comment by leeswimming** [comment]
통합 단계에 접어 들었으므로 해당 이슈를 종료합니다.
