### ISSUE TITLE
[Onion Messenger 구현] Client Nodelist

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-onion-team2#30]
Client side에서 nodelist 유지를 위한 개발은 client_nodelist에서 진행하도록 하겠습니다.

**Comment by Hexife** [comment]
확인했습니다.

**Comment by Hexife** [comment]
테스트 직전 코드 작성 완료했습니다. 코드 테스트 한 뒤 수정한 코드 업로드 하겠습니다.

**Comment by Hexife** [comment]
테스트 완료했습니다. PR후에 이 이슈는 닫힙니다.

**Comment by Hexife** [comment]
PR이 완료되어 이 이슈를 닫겠습니다. (#33)
