### ISSUE TITLE
[Onion Messenger 구현] Dockerfile 구성

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018s-onion-team2#35]
현재 Prototype으로 조금 작성을 해놨습니다만, Dockerfile에서 최종적으로 만족해야하는 것은 docker build를 했을 때 Container 설정, 환경 조성, 코드 Fetch, 컴파일,  호스트의 개인키 로딩 입니다.

구현이 완료 된 후 작업 진행이 필요합니다.

**Comment by Hexife** [comment]
현재 컨테이너 생성->필요파일 설치->유저생성->브랜치 다운로드 까지는 자동으로 진행되고,

프로젝트 완성 후에 프로그램 빌드 및 정리를 진행할 예정입니다.

**Comment by leeswimming** [comment]
As our development progresses, we are keep updating the docker file in the docker branch.

**Comment by soomin-kim** [comment]
이것도 일단 닫습니다

**Comment by soomin-kim** [comment]
너무 기게적으로 작업해서 실수했네요 ㅠㅠ 얘는 남겨두겠습니다

**Comment by Hexife** [comment]
도커파일의 구성은 완료 되었습니다. (#68 )

@elmisty 형이 Script 작업 완료를 하여 PR이 되면 이 이슈를 닫으면 될 것 같습니다.

**Comment by Hexife** [comment]
#70 이 Accept 되면 이 이슈를 닫아도 좋습니다.
