### ISSUE TITLE
[Onion Messenger 구현] make 구성

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018s-onion-team2#36]
프로젝트의 컴파일을 쉽고 일관적으로 할 수 있도록, make 파일을 구성해야 합니다.

이 부분도 코드 구현이 모두 끝나면 작업을 시작합니다.

Server, Client 모두 존재해야합니다.

Assignee 는 Server쪽은 @elmisty가, Client는 @leeswimming  또는 @Hexife가 진행하겠습니다.

**Comment by Hexife** [comment]
client make는 제가 만들겠습니다.

**Comment by Hexife** [comment]
server랑 통합하는 쪽으로 제작하는것이 좋아 보여서 이부분은 제가 맡겠습니다.

**Comment by leeswimming** [comment]
Since we already have  a makefile, I close this issue.
