### ISSUE TITLE
[Onion Messenger 구현] 통합 및 테스트

### ISSUE THREAD

**Issue by Hexife** [KAIST-IS521/2018s-onion-team2#38]
결과물을 모두 통합하여 테스트 합니다.

각 모듈 개발이 모두 종료되어 이슈가 closed 되면 진행합니다.

적어도 일요일 오후에는 진행되어야 하기에, 모든 개발은 그 전에 끝내 주시기 바랍니다.

**Comment by leeswimming** [comment]
통합하는 과정에서 많은 문제가 있어서 시간이 지연되고 있음

**Comment by soomin-kim** [comment]
일단 닫습니다
