### ISSUE TITLE
[TA] Very First After-Due-Date Works

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-onion-team2#50]
안녕하세요, 조교 김수민입니다.

안타까운 일이지만 듀데이트는 어제였고 아직 Team2의 Onion Messenger는 잘 작동하지 않는 상황입니다.
이에 대해서 교수님께서는 제가 여러분들을 도와서 다음주 안에 Onion Messenger를 완성시켜달라고 하셨습니다.
저는 실제로 프로그래밍을 하지는 않고, 여러분들께 각각 할 일을 분배하고, 진행상황을 점검하는 등의 일을 할 예정입니다.
앞으로 잘 부탁드립니다.

제일 처음으로 여러분들께서 해주셨으면 하는 일은 branch와 issue를 정리하는 것입니다.
저는 Team2의 Onion Messenger가 얼마나 개발이 되어있는지를 살펴보고 싶습니다.
그런데 이 repository에는 master branch를 제외하고 약 11개의 branch가 존재하고, comments와 본 issue를 제외하고 6개의 issues가 열려있어서 제가 살펴봐야 할 것들이 너무 많습니다.
갑자기 들어온 저보다는 여러분들이 현재 상황을 훨씬 더 잘 아실테니 제가 현 상황을 파악하는 것을 도와주셨으면 합니다.

- 각각의 branch들 중에서 현재 사용하지 않는 branch들은 제거해주시고, 그렇지 않은 branch들에 대해서는 본 issue에 현재 어떤 상황인지 간략하게 코멘트 달아주셨으면 좋겠습니다. 그럼 코멘트를 생각하며 branch를 살펴보도록 하겠습니다.
- 각각의 issue 역시 현재 상황과 상관없는 issue는 close해주시고, 그렇지 않은 issue들에 대해서는 현재 상황을 간단하게 코멘트 달아주셨으면 좋겠습니다.

가능한 빨리 해주실 수록 좋고, 늦어도 오늘 자정 전에 마쳐주셨으면 합니다.

저는 제가 할 수 있는 최대한으로 여러분들을 도울 예정입니다.
우리가 각자 역할을 잘 나눠서 맡은 바를 다한다면 이 프로젝트도 금방 끝낼 수 있을 것입니다!
다시 한 번 잘 부탁드립니다.

감사합니다.
김수민 드림

**Comment by soomin-kim** [comment]
다 끝나셨다면 여기에 Comment로 남겨주시면 됩니다 @leeswimming @Hexife @elmisty @hongsh93

**Comment by Hexife** [comment]
확인했습니다. 진행 후 추가 Comment 남기겠습니다.

**Comment by leeswimming** [comment]
안녕하세요, 팀리더입니다.

바쁘실텐데 저희가 일을 제 때 끝내지 못해 조교님께 번거로운 일을 만들어드려서 죄송합니다.
말씀하신대로 현재 진행상황을 정리해서 오늘 자정 전까지 알려드리도록 하겠습니다.

감사합니다.
이수영 드림

**Comment by leeswimming** [comment]
현재 각 component의 구현은 거의 이루어졌고 버그 확인이나 에러 헨들링을 하면서 통합하는 과정에 있습니다.
UI 작업을 하면서 통합을 함께 진행 중에 있습니다.
현재까지의 자세한 진행상황은 오프라인 미팅을 통해 조교님께 말씀드렸습니다.

**Comment by soomin-kim** [comment]
순조롭게 프로젝트를 마치길 바라며 본 이슈를 닫습니다.
