### ISSUE TITLE
Feedback from the professor / TAs

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-onion-team2#51]
안녕하세요, 조교 김수민입니다.

프레젠테이션 수고하셨습니다. 아래는 교수님과 조교들의 comments입니다.
- 편리함 vs. 보안 설명시 편리함을 포기했다고 이야기했음. 정말 "포기"한건가? 그렇다면 엄청난 실수는 아닌지?
- 보안, CIA, 등을 강조하지만, 이것은 본인들의 contribution이 아니라 onion messenger가 갖는 기본 속성이 아닌지?
- 발표 속도가 다소 느리며 산만함
- 라우팅 홉수에 따른 설정을 할 수 있는 부분은 좋은데, 그에 따른 성능 차이가 정말 얼마나 나는지? 얼마나 안전한지? 에 대한 설명이 부족
- 왜 깃허브아이디와 pub키 아이디를 동시에 사용해야하는지? 단순히 spec에 있어서라는 말을 하기 보단, TA 및 교수와 해당 이슈에 대해 상의하고 open mind로 접근했어야 했음. 다음부터는 이런 경우에 TA 아이디를 태그해서 직접 물어보도록.
- 개발 미완성 및 발표준비 부족
- 미완성이라도 발표시 본인들이 한 내용을 최대한 설명하면 더 좋을 것임.
- 대부분의 발표 내용이 굳이 설명할 필요가 없는 내용이었음
- 본인들이 구현한 것들에 내용은 마지막에 UI슬라이드 하나 빼고는 없음.
- 2주간 꾸준한 commit이라고 하기엔 너무 적음
- 차근차근 설명하려는 모습이 보임.
- interasting introduction
- Demo뿐만 아니라 implementation자체에 대한 진전이 없음.
- 이슈는 많지만 협력이 아니라 일방향 적인 요소가 보임
- Selling point도 보이지 않음
- Passion에 대해 설명한 슬라이드를 포함한 점 좋았습니다
- 슬라이드의 제목 및 내용의 배치가 어색한 슬라이드가 많았습니다.
- 시각화가 부족하고 지나치게 텍스트 위주로 설명하려는 면이 있었습니다.
- 개발 결과물의 차별점이나 특장점이 잘 와닿지 않았습니다.

김수민 드림

**Comment by Hexife** [comment]
확인했습니다.
