### ISSUE TITLE
[Rescue] Offline meeting

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-onion-team2#53]
안녕하세요, 김수민입니다.

내일 오후 2시 30분 이후 - 6시 이전에 Team2의 모든 분들과 만나서 이야기를 하고 싶습니다. 혹시 가능할까요?
가능 여부와, 가능하다면 시간을 알려주시면 감사하겠습니다.

김수민 드림

**Comment by Hexife** [comment]
저는 일단 모든 시간이 가능합니다.

**Comment by elmisty** [comment]
가능합니다.

**Comment by hongsh93** [comment]
가능합니다.  근데 5시 이전에 끝나야할것같습니다.

**Comment by leeswimming** [comment]
저도 다 가능합니다.

**Comment by soomin-kim** [comment]
그럼 3시에 투썸에서 만납시다!

**Comment by Hexife** [comment]
확인했습니다.  모두들 확인 할 수 있도록 카톡으로도 한번씩 연락을 하도록 하겠습니다.

감사합니다.

이택진 드림.

**Comment by soomin-kim** [comment]
정상적으로 진행하였으므로 본 이슈를 닫습니다
