### ISSUE TITLE
[Rescue] 1st Prototype

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-onion-team2#55]
안녕하세요, 김수민입니다.

조금 전에 Offline 회의를 통해 결정된 첫번째 Prototype과 관련된 이슈입니다.
다음과 같은 기능을 갖는 Prototype을 생성하는 것이 본 이슈의 목표입니다.

Onion Messenger Client with the following functionalities:
 - Message encryption with an onion routing path
 - Send message to other client
 - Receive message from other client
 - Message decryption
with the following assumptions:
 - client identifier : ip , port
 - onion routing path is given
 - messages can be given
 - gpg pub keys are given

Expected Result:
 - B, C, D, E가 돌고 있을 때 A로부터 E로 메시지를 보냄
 - B, C, D는 정상적으로 메시지를 수신하지만, 내용을 알 수는 없음
 - E는 정상적으로 메시지를 수신하고, 내용을 암

감사합니다.
김수민 드림

**Comment by leeswimming** [comment]
넵 확인했습니다.
