### ISSUE TITLE
[Rescue] UI

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-onion-team2#56]
안녕하세요, 김수민입니다.

Prototype이 발전해나가는 동안, 구현이 안 되어 있는 UI를 구현해나가는 것이 시간 절약에 도움이 될 것입니다.
UI 작업은 source_code directory에서 일단 하시고, 나중에 Prototype에 붙이시면 될 것 같습니다.
Branch를 만들어두겠습니다.

김수민 드림

**Comment by Hexife** [comment]
확인했습니다. 
가장 간단한 CLI 형태로 진행하도록 하겠습니다.

**Comment by Hexife** [comment]
현재 구현 계획은 transmission 쪽의 recv 관련 thread를 활용하며 ( 물론 이는 **잘 동작한다**고 가정합니다. ), 메세지큐를 구현하고 이를 출력하는 thread 1개, 사용자로부터의 입력 및 send하는 thread 1개로 구성하려고 합니다. 

출력은 format정도만 지키며 그 외에 design은 생각하지 않을 예정입니다.

정리하면 3개의 thread는 각각 다음과 같이 동작 하는 것을 기대하며 개발할 예정입니다.
1. transmission의 recv listener thread : 메세지가 들어오면 메세지 큐에 저장하는 메소드를 이용하여 큐에 삽입. 구현 된 것이 **잘 동작 한다**고 생각하며, UI 개발단계에서는 배제합니다.
2. OUTPUT thread : 메세지 큐에 저장하는 메소드가 실행되면 큐에 저장을 하고 화면을 refresh시킵니다.
3. INPUT/SENDER thread : 사용자로부터 입력을 받고 0x0a가 입력된 순간 메세지 큐에 저장하고 sender 함수를 이용해 타 client로 전송합니다. 물론 sender 함수는 **잘 동작 한다** 고 가정하며 UI 구현단계에서는 배제합니다.

**Comment by Hexife** [comment]
현재 쓰레드를 제외하고 IO만 있는 버전이 56-UI Branch에 올라가 있습니다.

**Comment by soomin-kim** [comment]
2nd Prototype에 담긴 UI와 UI branch가 연관이 없다면 알려주세요. UI branch를 정리하도록 하겠습니다.

**Comment by Hexife** [comment]
UI는 Prototype2에 합쳐졌습니다. 따라서 UI branch는 정리해도 될 것으로 생각됩니다.

**Comment by soomin-kim** [comment]
알겠습니다.
UI branch를 삭제하도록 하겠습니다.
