### ISSUE TITLE
[Rescue] Testing 1st Prototype

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-onion-team2#57]
안녕하세요, 김수민입니다.

아직 첫 번째 프로토타입이 완성되지는 않았지만, 완성되는 대로 본 이슈를 해결해주시면 좋을 것 같습니다.
다음과 같은 일들을 해주셨으면 합니다.
 - Docker를 이용하여 동시에 5개의 instance를 실행
 - #55 에 명시되어있는 Expected Result를 만족하는지 확인

감사합니다.
김수민 드림

**Comment by hongsh93** [comment]
확인했습니다.

**Comment by elmisty** [comment]
확인했습니다.

**Comment by hongsh93** [comment]
Hello -> Hell
HELLO -> HELL
hello -> hell
hellow -> hellow
ooooooo -> ooooooo
abcde -> abcd
abcd -> abcd
abc -> abc▒
ab -> ab
a -> a
123 -> 123▒
메세지가 5글자와 3글자일 때 오류가 발생하는것 같습니다. 확인바랍니다.

**Comment by hongsh93** [comment]
12345678 -> 12345678x
123456789 -> 123456789
1234567890 -> 1234567890
12345678901 -> 12345678901▒
123456789012 -> 123456789012
1234567890123 -> 123456789012

8, 11, 13글자일 때도 오류가 있네요. 14글자 이상은 테스트해보지 않았습니다.

**Comment by hongsh93** [comment]
8글자 올라갈때마다 오류가 발생하는것 같아서 좀더 테스트해본결과
1234567890123456 -> 1234567890123456andra@de5
이고 16글자 ~ 25글자는 전부 오류가 발생합니다.

**Comment by leeswimming** [comment]
I cannot reproduce this bug. We will see if this still happens in our 2nd prototype.

**Comment by leeswimming** [comment]
확인해봤는데 말씀하신 것과 정확히 케이스가 같은 건 아니지만 문제가 있는 걸 확인했습니다.

**Comment by leeswimming** [comment]
I have found a bug in copying the recevied message and fixed it. (#66)

**Comment by soomin-kim** [comment]
2nd prototype이 거의 다 완성되어가는 상황이므로 2nd prototype testing으로 옮겨가는 방향으로 가면 좋을 것 같습니다.
