### ISSUE TITLE
[Rescue] Update README.md

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-onion-team2#58]
안녕하세요, 김수민입니다.

아까 회의한 것처럼, 프로토타입이 가정으로 깔고 가는 사항들을 포함하여 여러가지들을 [README.md](https://github.com/KAIST-IS521/2018s-onion-team2/blob/master/README.md)에 업데이트 해주셨으면 합니다!

감사합니다.
김수민 드림

**Comment by Hexife** [comment]
넵 곧 업데이트 하겠습니다.

**Comment by Hexife** [comment]
업데이트 완료 하였습니다. 확인 후 의견 또는 close 부탁 드립니다.
