### ISSUE TITLE
[help] docker container shell 실행방법이 어떻게 되나요?

### ISSUE THREAD

**Issue by hongsh93** [KAIST-IS521/2018s-onion-team2#59]
docker branch에서 docker container shell을 실행하는 방법을 모르곘습니다

**Comment by Hexife** [comment]
전에 아무 스크립트도 실행되지 않았으면 다음과 같이 해야 합니다
1. setdocker.sh 실행 
- setdocker.sh는 Docker의 네트워크 환경 및 Docker image를 build 해주는 스크립트 입니다.

2. run.sh 실행
- run.sh는 build된 image를 container로 만들어주고 실행시켜 주는 스크립트 입니다. 
* run.sh는 ./run.sh [ container name ] [ ssh port ] 로 실행시키시면 됩니다. 예시는 아래와 같습니다.
EX> ./run.sh do 50000 => onion_do 라는 컨테이너가  돌아가기 시작하며 50000번 포트는  컨테이너의 22번 포트로 포워딩 됩니다. 
* server용으로 만들 시 [ containter name ] 을 server로 해주면 서버용이 만들어 집니다. 서버용은 ip가 172.20.254.254로 고정입니다.

3. (개발용) exec_sh.sh 실행
- exec_sh.sh 는 개발 테스트 등에만 사용될 스크립트며, exec_sh.sh [ container name ]으로 실행시키시면 됩니다.
EX> ./exec_sh.sh onion_do => onion_do의 쉘이 뜹니다.

더 설명이 필요하시면 댓글로 남겨주시고, 충분히 설명이 되었다면 close 해주시기 바랍니다.

**Comment by hongsh93** [comment]
![2018-04-04 19 42 42](https://user-images.githubusercontent.com/22565656/38303231-61874bbe-3840-11e8-963b-ad620c4dd5cb.PNG)
처음에 set docker.sh를 실행하면 다음과 같은 오류가 발생하는데 그 전에 해야하는 명령이 있나요?

docker라는 명령어가 없다고 뜨네요

**Comment by Hexife** [comment]
제가 하나 빠트렸네요. 모든 명령어는 docker의 특성상 **root 권한으로 진행해야**합니다. (일반 계정은 sudo 사용) 하지만 저 경우에는 docker가 설치되지 않는 것으로 추정됩니다.

**Comment by hongsh93** [comment]
넵 저기있는 3번까지 전부 실행되고나면 issue를 close하겠습니다.

**Comment by hongsh93** [comment]
3번까지 모두 해결되었으므로 issue를 종료하겠습니다.
