### ISSUE TITLE
[급함] 1st prototype 명령어

### ISSUE THREAD

**Issue by hongsh93** [KAIST-IS521/2018s-onion-team2#62]
1st prototype를 테스트 하기위해 설정해둔 명령어를 알려주면 좋을것 같습니다.

**Comment by leeswimming** [comment]
1. git pull 한 다음에 make를 입력하시면 컴파일이 됩니다.
(만약 도커에 make가 설치되어 있지 않으면 sudo apt-get install make 하시면 됩니다.)
2. receiver나 패킷이 거쳐가는 client들은 ./client -p passphrase 처럼 passphrase를 -p 옵션을 줘서 실행하시면 됩니다.
3. sender는 ./client -m Hello -r "172.20.0.3:172.20.0.4:172.20.0.5" 이런식으로 실행하면
127.20.0.3 => 127.20.0.4 => 172.20.0.5의 순서로 Hello라는 메시지를 전송하겠다는 뜻이 됩니다.

P.S. 2번을 모두 켜신 다음에 3번을 켜야 에러가 나지 않습니다.

**Comment by hongsh93** [comment]
확인했습니다.
