### ISSUE TITLE
[Rescue] 2nd Prototype

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-onion-team2#63]
안녕하세요 김수민입니다.

다음 목표는 client-side의 (거의) 완성입니다.
두 번째 Prototype에 추가되어야 할 기능들은:
 - User들에 대한 정보를 담고 있는 클래스 추가
 - Onion routing path generation
 - UI 입히기
등이 되겠습니다.

Expected Result:
 - client를 실행할 때 인자로 주는 것은 네트워크 내의 모든 실행중인 messenger instance들에 대한 정보(id, ip, ...) 인자로 안받고 프로그램 시작시에 메모리에 올려도 됩니다.
 - client가 실행되면 본인의 id를 입력할 수 있어야 합니다.
 - 현재 접속중인 사용자들의 목록을 볼 수 있어야 합니다.
 - 메시지를 보낼 사용자의 id / 내용을 입력할 수 있어야 합니다.

역할 분담:
1st prototype에서 @leeswimming 님이 맡았던 역할을 @Hexife 님이 맡아주시면 됩니다.
@leeswimming 님은 @Hexife 님을 서포트해주시면 됩니다.
@elmisty 님은 최대한 빨리 UI를 완성해주세요. 이 이슈의 듀데잍 전에 무조건 완성하셔야 합니다.
@hongsh93 님은 테스팅을 맡아주시면 됩니다.

Due Date:
4월 6일 11시 59분

이게 성공적으로 끝나면 Server 개발하고 마무리 하면 될 것 같습니다.
성공적인 마무리 기원합니다.

김수민 드림

**Comment by leeswimming** [comment]
넵 확인했습니다

**Comment by Hexife** [comment]
확인했습니다. 아주 조금의 오류가 있는데, 이미 유저들 리스트는 prototype에서 들고 있습니다.

제가 금일 저녁~내일 오후에 개인적인 사정으로 작업을 원활히 못하는 것을 미리 알리며 듀데이트 지킬수 있도록 하겠습니다.

**Comment by Hexife** [comment]
시간을 잘못 봤었네요.. 오늘 까지구나... @elmisty  일어나시면 구현된거 바로 올려주세요. 일단 그걸로 올리고 있을게요

**Comment by hongsh93** [comment]
확인했습니다.

**Comment by Hexife** [comment]
현재 진행상황입니다.

채팅창 UI는 붙긴 했지만, 송신시 encryption message가 빠져서 2번째 노드에서 실패합니다. ( 오늘 생긴 버그 입니다.)

그리고 큐에 안들어 가는 문제와 수신과정에서 Double Free 문제가 있는데 이는 연관된 버그로 판단됩니다.

마지막으로 메세지 통신에 실패하면(노드가 존재하지 않을때) bash 쉘에서 문자열이 출력 안되는 버그가 있습니다.

이정도만 고치고, 로그인 UI ( 기존 @leeswimming 이 제작하던 UI를 가져올 생각입니다.) 을 붙이면 이번 프로토 타입은 완성될 듯 싶습니다.

기한이 많이 늦어졌네요.. 최대한 빠르게 마치도록 하겠습니다.

**Comment by Hexife** [comment]
쉘버그 / encryption message 는 버그 수정 되었으나, 여전히 다른 클라이언트는 메세지를 받지 못하고 있습니다. 

진행되는 대로 이슈 코멘트 남기겠습니다.

**Comment by Hexife** [comment]
송수신이 100%확률은 아니지만 간헐적(30%정도)으로 되는 것을 확인하였습니다. 

랜덤 Path 생성에서 문제가 생겼을 가능성이 커보입니다.("5번 컨테이너에 데이터가 전혀 가지 않음")

남은 문제는 1. 패킷 손실? 2. 패킷 훼손 (글씨 깨짐 문제)가 있습니다.

1번 문제는 @Hexife가 더 진행하면서 알아봐야 되고 , 
2번 문제는 prototype때도 존재했던 문제이므로 @leeswimming 과 같이 보겠습니다.

현재  UI는 @elmisty가 붙이기 작업을 하고 있습니다.

**Comment by Hexife** [comment]
추가 버그 : 채팅창에서 /를 이용했을 때 문자열 자르는 부분에서 오류..

**Comment by Hexife** [comment]
현재 Message pulling 을 제외하고 모든 작업이 완료 상태입니다.

**Comment by Hexife** [comment]
@elmisty 님의 작업이 끝나면 종료하는 것으로 하면 좋을 듯 싶습니다.

자잘한 버그 외에 기능이 정상적으로 동작합니다.

**Comment by Hexife** [comment]
@leeswimming 과 함께 남은 버그를 처리하고 있습니다. 버그 처리 완료 후 PR이 완료되면 이 이슈를 닫겠습니다.

**Comment by Hexife** [comment]
최종 PR 입니다 #71
