### ISSUE TITLE
[Rescue] 불필요한 함수 리스트

### ISSUE THREAD

**Issue by leeswimming** [KAIST-IS521/2018s-onion-team2#65]
최종 prototype에서 사용하지 않아서 불필요해 보이는 class 또는 method의 리스트입니다.

## Server Side
- list_node.hh의 list_node class
- list_check.hh의 list_check class
- hb_server.hh의 hbchecker class
- hb_node.hh의 hb_node

위 class들은 이미 client side에 모두 구현되어있습니다.

## Client Side
- util.hh의 util::time_t2byte, util::byte2time_t은 timestamp.hh에 이미 구현되어 있습니다.
- usserInfo class의 mode 및 관련 함수는 새로운 디자인에서는 불필요해보입니다.
- 현재 ui가 수정 중에 있으므로 ui.hh의 함수들도 사용하지 않는다면 정리가 필요해보입니다.
- transmission.hh의 tmd::tmdPackPacket도 불필요해보입니다.
- 최종 ui의 디자인에 따라 timestamp::tmestamp2str 함수도 필요여부를 결정해야 할 것으로 보입니다.
- parser.hh에도 현재 사용하지 않는 함수들이 있는데 마지막에 확인을 할 필요가 있습니다.
- message.hh와 nodelist.hh는 현재 2nd prototype의 개발에 사용 중이니 이후에 확인이 필요합니다.
- gpg.hh의 gpg::keyRefresh, gpg::recvPubKey는 우리의 가정에 따라 삭제하여도 좋을 것으로 보입니다.
- config 파일도 불필요해보입니다.

확인부탁드립니다.

**Comment by Hexife** [comment]
버그를 제거하면서 조금씩 불필요한 함수를 제거 하고 있습니다.

**Comment by Hexife** [comment]
#71 에 포함되었습니다.
