### ISSUE TITLE
[Rescue] 2nd Prototype Testing

### ISSUE THREAD

**Issue by soomin-kim** [KAIST-IS521/2018s-onion-team2#67]
안녕하세요, 김수민입니다.

두 번째 버전의 프로토타입이 최종 submission version이 될 것 같으므로,
본 이슈가 마지막 major 이슈가 될 것 같습니다.
2nd prototype이 완성되는 대로, @hongsh93 님과 @elmisty 님이 제대로 작동하는지 테스트 반드시 해주시기 바랍니다.
감사합니다.

김수민 드림

**Comment by elmisty** [comment]
UI 테스트 진행상황

1. 메인 UI
: ncurses로 작동하던 기존의 UI 폐기 후, 간단한 UI로 변경
[180408] 작성완료 - 자잘한 버그 잡는데 중점을 둘 예정
  - 백스페이스가 안먹는 버그 발생에 따른 버그 수정중

2. 기능추가 
: 현재까지 사용 후 종료 전까지 추가할 수 있는 기능 추가예정이며, 추가할 기능이 생길 경우 슬랙 및 이슈에 먼저 말씀드리겠습니다.

**Comment by leeswimming** [comment]
1. 정상적인 종료가 되지 않는 문제 해결
2. 사용자 Public Key ID 길이 확인
3. Application 실행을 위한 Script 작성

위의 세 가지를 진행중이며, 해당 사항들이 모두 완료될 경우 최종 완성됩니다.

**Comment by Hexife** [comment]
현재 로그인 화면에서 ID 입력시 backspace가 작동을 하지만 visual하게 보이지 않는 점을 확인하고 있습니다.

@leeswimming 의 전 코멘트에서 1번 은 해결 완료, 2번은 string으로 관리되고 있는 데다, 유효성 검사를 하므로 코드 추가를 같이 검토하겠습니다. 3번은  @elmisty 형이 작성 하고 있습니다.

빠른시일내에 끝낼 수 있도록 하겠습니다.

**Comment by Hexife** [comment]
현재 Submit 한 버전을 테스트 해보시면 될 듯 싶습니다.

개인적으로 간단하게 테스트 했을 때는 잘 동작하는 것을 확안하였습니다.
