### ISSUE TITLE
There is a command injection vulnerability

### ISSUE THREAD

**Issue by zanywhale** [KAIST-IS521/2018s-onion-team2#73]
In checking passphrase, it can not detect abnormal input.
So I can get shell :)
Payload is ` ' > ls&/bin/bash 0>&2 1>&2 #`

![image](https://user-images.githubusercontent.com/26449129/38539024-4d8c499e-3cd1-11e8-9d81-f0c44f8a2b30.png)

**Comment by Hexife** [comment]
I confirmed and I will check your solution. Thank you for your report.

**Comment by Hexife** [comment]
I checked your solution. Your patch code seems to check passphrase enough. Thank you for your awesome patch. PR #74 ACCEPTED
